### ISSUE TITLE
Feature request: support for require

### ISSUE THREAD

**Issue by Jemt** [olefjaerestad/vscode-circular-dependencies-finder#11]
Hi,

Thank you for creating this extension :-)

I would love to see support for require. I did a quick test - it doesn't seem to be supported.

File a.js requires b.js.
File b.js requires a.js
File index.js requires a.js

The result comes back with: Found no circular dependencies

-- Thanks :-)

**Comment by olefjaerestad** [comment]
Hi! Apologies for the late reply. Thanks for the feedback. I'm trying to reproduce the reported behaviour, but have been unable so far. Could you share a minimal repro (i.e. file structure and file contents)? And which file are you entering in the 'Find Circular Dependencies' command?
