### ISSUE TITLE
Option to exclude type imports

### ISSUE THREAD

**Issue by adi518** [olefjaerestad/vscode-circular-dependencies-finder#16]
Cool extension. Can you add an option to exclude `import type` statements? they do not affect runtime, so in some cases they are just false positives.

**Comment by olefjaerestad** [comment]
Hi! It makes sense to be able to exclude `import type` statements. Do you ever see it as useful to include them, or would it be a better default to exclude them?

**Comment by adi518** [comment]
For circular they are ignorable. It should be toggleable.

**Comment by olefjaerestad** [comment]
Agreed. I'll work on the feature and report back when it's ready!

**Comment by olefjaerestad** [comment]
Hi again, @adi518! An option to exclude `import type` statements has now been added: `'circularDependenciesFinder.excludeTypeImports'`. You find it in VSCode's settings menu (cmd + ',' on mac). It's worth noting that this will only exclude type imports using `import type`; type imports using `import` without `type` will always be included.

The option is available in version 1.2.0 ([changelog](https://marketplace.visualstudio.com/items/olefjaerestad.vscode-circular-dependencies-finder/changelog)). Hope it works well for you. Thanks for the feedback!
